# Generated by Django 5.0.6 on 2024-07-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='imgage',
            new_name='image',
        ),
    ]
