# Generated by Django 5.0.6 on 2024-07-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_imgage_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_img/default-profile.jpg', null=True, upload_to='profile_img'),
        ),
    ]
