# Generated by Django 5.0.6 on 2024-07-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Product_Image',
        ),
    ]
