# Generated by Django 5.0.6 on 2024-07-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_productimage_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Image',
            new_name='ProductImage',
        ),
    ]
